name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Direct download URL for vmlinux.zip'
        required: true
      # 移除 PERF_DATA_URL，因为 perf.data 将直接从 raw.githubusercontent.com 下载

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y curl unzip

      - name: Download and extract create_llvm_prof binary
        run: |
          curl -LO https://github.com/google/autofdo/releases/download/v0.30.1/create_llvm_prof-x86_64-v0.30.1.zip
          unzip create_llvm_prof-x86_64-v0.30.1.zip
          chmod +x create_llvm_prof

      - name: Download and unzip vmlinux.zip
        run: |
          curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux.zip
          unzip -j vmlinux.zip vmlinux -d .

      - name: Clone egcd521/build-afdo repo (含 perf.zip)
        run: |
          git clone https://github.com/3620603660/afdo_89.git
          ls -lh afdo_89/perf.data

      - name: Generate kernel.afdo
        run: |
          ./create_llvm_prof --binary=vmlinux --profile=perf.data --out=kernel.afdo

      - name: Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo