name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Direct download URL for vmlinux.zip'
        required: true

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip curl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone afdo_89 repo and extract perf.zip
        run: |
          git clone https://github.com/3620603660/afdo_89.git -o perf.zip
          unzip -o afdo_89/perf.zip -d afdo_89
          ls -lh afdo_89

      - name: Download and extract create_llvm_prof binary
        run: |
          curl -LO https://objects.githubusercontent.com/github-production-release-asset-2e65be/18347398/9190e1e8-6f14-4054-b85f-f974d8a43549?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250701%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250701T154406Z&X-Amz-Expires=1800&X-Amz-Signature=ebac043340f8f06d7cf4749412a61f3ec99102472d1e5d0d39cc6bf755b6465e&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dcreate_llvm_prof-x86_64-v0.30.1.zip&response-content-type=application%2Foctet-stream
          unzip create_llvm_prof-x86_64-v0.30.1.zip
          chmod +x create_llvm_prof

      - name: Download and unzip vmlinux.zip
        run: |
         curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux.zip
         unzip -j vmlinux.zip vmlinux -d .
         ls -lh vmlinux

      - name: Generate kernel.afdo
        run: |
          ./create_llvm_prof --binary=vmlinux --profile=perf.data --out=kernel.afdo

      - name: Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo

      - name: Cleanup
        run: |
          rm -rf afdo_89 create_llvm_prof-x86_64-v0.30.1.zip vmlinux.zip