name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Direct download URL for vmlinux.zip'
        required: true

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y curl unzip git # 确保 git 已安装

      - name: Download and extract create_llvm_prof binary
        run: |
          curl -LO https://github.com/google/autofdo/releases/download/v0.30.1/create_llvm_prof-x86_64-v0.30.1.zip
          unzip create_llvm_prof-x86_64-v0.30.1.zip
          chmod +x create_llvm_prof

      - name: Download and unzip vmlinux.zip
        run: |
          curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux.zip
          unzip -j vmlinux.zip vmlinux -d .
          ls -lh vmlinux # 增加验证步骤

      - name: Clone repository with perf.data
        run: |
          git clone https://github.com/3620603660/afdo_89.git
          echo "--- Verifying file path ---"
          ls -lh afdo_89/perf.data # 验证 perf.data 确实在子目录中

      - name: Generate kernel.afdo
        run: |
          echo "Running AFDO profile generation..."
          # 修正：为 --profile 参数提供正确的相对路径
          ./create_llvm_prof --binary=vmlinux --profile=afdo_89/perf.data --out=kernel.afdo

      - name: Verify output and Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo