name: Compile perf

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_ace5_pro'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'

jobs:
  compile-perf:
    runs-on: ubuntu-latest

    steps:
      - name: Download Android source code
        uses: actions/checkout@v2
        with:
          repository: android/platform_manifest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Download and compile Android source code
        run: |
          repo init -u $ https://github.com/3620603660/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
          repo sync
          source build/envsetup.sh
          lunch aosp_arm-eng
          make -j$(nproc)

      - name: Install perf binary
        run: |
          cp out/target/product/generic_arm/obj/KERNEL_OBJ/usr/bin/perf /usr/bin/perf
