name: ace5pro_kernel_6.6合并100

on:
  workflow_dispatch:
    inputs:
      CPU_ARCH:
        description: "目标CPU架构分支，例如 sm8750 (默认: sm8750)"
        required: true
        default: 'sm8750'
      DEVICE_CONFIG:
        description: "设备配置文件名称，例如 oneplus_ace5_pro (默认: oneplus_ace5_pro)"
        required: true
        default: 'oneplus_ace5_pro'
      ANDROID_TARGET_VERSION:
        description: "目标Android版本，例如 android15 (默认: android15)"
        required: true
        default: 'android15'
      KERNEL_BASE_VERSION:
        description: "内核基础版本，例如 6.6 (默认: 6.6)"
        required: true
        default: '6.6'
      CUSTOM_KERNEL_NAME_TAG:
        description: "自定义内核名称标识，将附加到内核版本号后 (例如: -android15-8-g29d86c5fc9dd-abogki428889875-4k)"
        required: false
        default: '-android15-8-g29d86c5fc9dd-abogki428889875-4k'
        type: string
      LOCAL_VERSION_SUFFIX:
        description: '内核版本后缀（如-v8，默认：空）'
        required: false
        default: ''
        type: string
      REMOVE_DEFAULT_4K_SUFFIX:
        description: '是否删除默认的 -4k 后缀？（勾选则删除）'
        required: false
        default: true
        type: boolean
      BUILD_TIMESTAMP:
        description: '内核构建时间 (UTC格式，例如 "Tue Dec 17 23:36:49 UTC 2024")'
        required: false
        default: 'Tue Jul 1 19:48:18 UTC 2025'
        type: string

env:
  WORKSPACE_DIR: kernel_workspace
  KERNEL_PLATFORM_DIR: ${{ github.workspace }}/kernel_workspace/kernel_platform
  CCACHE_DIR: /home/runner/.ccache
  CCACHE_MAXSIZE: 8G
  CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
  CCACHE_NOHASHDIR: "true"
  CCACHE_HARDLINK: "true"
  KSU_VERSION_BASE: 10606

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TOKEN: ${{ secrets.TOKEN }}
    
    steps:
      - name: 1.1 最大化构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: 1.2 配置Git用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 1.3 检出工作流仓库代码  
        uses: actions/checkout@v4  

      - name: 1.4 安装构建核心依赖  
        run: |  
          sudo apt-get update  
          sudo apt-get install -y --no-install-recommends \
            python3 git curl ccache libelf-dev build-essential \
            bc bison flex libssl-dev libncurses5-dev

      - name: 2.1 恢复 ccache 缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-v3_pro
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-ccache-
            ${{ runner.os }}-${{ github.repository }}-ccache-
            ${{ runner.os }}-ccache-
    
      - name: 2.2 配置 ccache
        run: |  
          echo "CCACHE_BASEDIR=${{ github.workspace }}" >> $GITHUB_ENV  
          echo "CCACHE_LOGFILE=${{ github.workspace }}/ccache.log" >> $GITHUB_ENV  
          echo "/usr/lib/ccache" >> $GITHUB_PATH  
         
      - name: 2.3 显示 ccache 统计信息
        run: |
          ccache -s || true
         
      - name: 3.1 安装 repo 工具
        run: |
          curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: 3.2 初始化并同步内核源码
        run: |
          mkdir -p ${{ env.WORKSPACE_DIR }} && cd ${{ env.WORKSPACE_DIR }}
          repo init -u https://github.com/3620603660/kernel_manifest.git \
            -b refs/heads/oneplus/${{ github.event.inputs.CPU_ARCH }} \
            -m ${{ github.event.inputs.DEVICE_CONFIG }}.xml --depth=1
          repo sync -c -j$(nproc) --no-tags --no-clone-bundle
          
          # 清理不需要的文件
          rm -f kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports to remove."
          rm -f kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports to remove."
         
      - name: Set up SukiSU
        run: |
         cd ${{ env.KERNEL_PLATFORM_DIR }}
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
         cd ./KernelSU
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" ${{ env.KSU_VERSION_BASE }})
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Set up SUSFS & apply patches
        run: |
         set -e
         
         cd ${{ env.WORKSPACE_DIR }}
         git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_TARGET_VERSION }}-${{ github.event.inputs.KERNEL_BASE_VERSION }}
         git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git
         git clone https://$TOKEN@github.com/3620603660/boot.git
         cd ${{ env.KERNEL_PLATFORM_DIR }}
         cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_TARGET_VERSION }}-${{ github.event.inputs.KERNEL_BASE_VERSION }}.patch ./common/ || true
         mkdir -p ./common/fs ./common/include/linux ./common/lib ./common/crypto
         cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/ || true
         cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/ || true
         cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux || true
         cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib || true
         cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto || true
         cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/ || true
         cp ../boot/1.patch ./common/
         cd ./common
         PATCH_FILE=50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_TARGET_VERSION }}-${{ github.event.inputs.KERNEL_BASE_VERSION }}.patch
         # sed -i 's/-32,12 +32,38/-32,11 +32,37/g' "$PATCH_FILE"
         # sed -i '/#include <trace\/hooks\/fs.h>/d' "$PATCH_FILE"
         if [[ -f "$PATCH_FILE" ]]; then
         patch -p1 < "$PATCH_FILE" || true
         fi
         cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
         patch -p1 -F 3 < syscall_hooks.patch || true
         patch -s -p1 -F 3 < 1.patch
         echo "✅ SUSFS 和 syscall_hooks patch 应用完成"

      - name: Apply Hide Stuff Patches
        run: |
          cd ${{ env.KERNEL_PLATFORM_DIR }}/common
          cp ../../SukiSU_patch/69_hide_stuff.patch ./
          echo "正在打隐藏应用补丁"
          patch -p1 -F 3 < 69_hide_stuff.patch
          echo "隐藏应用_patch完成"
         
      - name: 设置内核优化配置
        run: |
          cd ${{ env.KERNEL_PLATFORM_DIR }}
          CONFIG_FILE="./common/arch/arm64/configs/gki_defconfig"
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Error: 配置文件 $CONFIG_FILE 不存在"
            exit 1
          fi
          
          # 移除可能存在的旧优化配置，防止重复
          sed -i '/# Optimizations Start/,/# Optimizations End/d' "$CONFIG_FILE"

          # 将新的、完整的优化配置追加到文件末尾
          cat >> "$CONFIG_FILE" << 'EOF'

          # Optimizations Start: 由 Manus AI 优化和整合

          # 1. KernelSU & SUSFS (基础功能)
          CONFIG_KSU=y
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_MANUAL_HOOK=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_KSTAT=y
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          CONFIG_KPM=y

          # 2. CPU与电源管理
          CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
          CONFIG_CPU_IDLE_GOV_TEO=y
          CONFIG_SCHED_CORE=y
          CONFIG_UCLAMP_TASK=y
          CONFIG_SCHED_HRTICK=y

          # 3. 内存管理
          CONFIG_LRU_GEN=y
          CONFIG_ZRAM=y
          CONFIG_ZRAM_LZ4=y
          CONFIG_ZRAM_ZSTD=y
          CONFIG_ANDROID_LOW_MEMORY_KILLER=y

          # 4. 网络性能优化
          # 4.1 拥塞控制算法 (BBRv3 + Brutal)
          CONFIG_DEFAULT_TCP_CONG="bbr"
          CONFIG_TCP_CONG_BBR=y
          CONFIG_TCP_CONG_BRUTAL=y
          CONFIG_TCP_CONG_BIC=n
          CONFIG_TCP_CONG_CUBIC=n
          CONFIG_TCP_CONG_WESTWOOD=n
          CONFIG_TCP_CONG_HTCP=n
          # 4.2 基础网络优化
          CONFIG_NET_SCH_CAKE=y
          CONFIG_NET_SCH_FQ=y
          CONFIG_DEFAULT_NET_SCH="cake"
          CONFIG_TCP_FASTOPEN=y
          # 4.3 全锥形 NAT (Full Cone NAT)
          CONFIG_NF_CONNTRACK=y
          CONFIG_NF_CONNTRACK_EVENTS=y
          CONFIG_NF_CONNTRACK_MARK=y
          CONFIG_NETFILTER_ADVANCED=y
          CONFIG_NETFILTER_XTABLES=y
          CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
          CONFIG_NETFILTER_XT_TARGET_FULLCONENAT=y
          # 4.4 Shortcut-FE (高通网络加速)
          CONFIG_NET_SHORTCUT_FE=y
          CONFIG_NET_SHORTCUT_FE_USER=y

          # 5. 编译与构建优化
          CONFIG_LTO_CLANG_THIN=y
          CONFIG_LTO_POLLY=y

          # 6. 虚拟化与容器化
          # 6.1 KVM 虚拟化
          CONFIG_VIRTUALIZATION=y
          CONFIG_KVM=y
          CONFIG_KVM_ARM_HOST=y
          # 6.2 Docker 支持 (核心依赖)
          CONFIG_NAMESPACES=y
          CONFIG_NET_NS=y
          CONFIG_PID_NS=y
          CONFIG_IPC_NS=y
          CONFIG_UTS_NS=y
          CONFIG_CGROUPS=y
          CONFIG_CGROUP_CPUACCT=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_CGROUP_FREEZER=y
          CONFIG_CGROUP_SCHED=y
          CONFIG_CPUSETS=y
          CONFIG_MEMCG=y
          CONFIG_KEYS=y
          CONFIG_VETH=y
          CONFIG_BRIDGE=y
          CONFIG_BRIDGE_NETFILTER=y
          CONFIG_NF_NAT=y
          CONFIG_IP_NF_FILTER=y
          CONFIG_IP_NF_TARGET_MASQUERADE=y
          CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
          CONFIG_NETFILTER_XT_MATCH_IPVS=y
          CONFIG_IP_VS=y
          CONFIG_IP_VS_NFCT=y
          CONFIG_IP_VS_RR=y
          CONFIG_OVERLAY_FS=y

          # 7. 硬件与安全
          # 7.1 硬件随机数
          CONFIG_HW_RANDOM=y
          CONFIG_HW_RANDOM_MSM=y
          # 7.2 硬件加密
          CONFIG_CRYPTO_HW=y
          CONFIG_CRYPTO_DEV_QCE=y

          # 8. 文件系统
          CONFIG_F2FS_FS_LZ4=y
          CONFIG_F2FS_FS_ZSTD=y
          CONFIG_EROFS_FS=y
          CONFIG_EROFS_FS_ZIP=y
          CONFIG_EROFS_FS_LZ4=y

          # 9. 设备特定优化
          CONFIG_NVME_TARGET=y
          CONFIG_BT_QCA=y
          CONFIG_ARM64_SME=n

          # Optimizations End
          EOF
          
          # 确保 gki_defconfig 中的 check_defconfig 不会干扰构建
          sed -i 's/check_defconfig//' ./common/build.config.gki
          git add -A && git commit -a -m "feat: Integrate advanced kernel optimizations by Manus AI" || true
          echo "✅ 内核优化配置已完成并提交"
          
      - name: 7.1 修改内核版本显示名称
        run: |
          cd ${{ env.KERNEL_PLATFORM_DIR }}
          sed -i 's|^echo ".*"|echo "${KERNELVERSION}${scm_version}${config_localversion}"|' common/scripts/setlocalversion
          if [ -n "${{ github.event.inputs.CUSTOM_KERNEL_NAME_TAG }}" ]; then
            sed -i "s/\${scm_version}/${{ github.event.inputs.CUSTOM_KERNEL_NAME_TAG }}/g" ./common/scripts/setlocalversion
          fi
         
      - name: 7.2 设置 CONFIG_LOCALVERSION
        run: |
          cd ${{ env.KERNEL_PLATFORM_DIR }}
          if [ -n "${{ github.event.inputs.LOCAL_VERSION_SUFFIX }}" ]; then
            echo 'CONFIG_LOCALVERSION="${{ github.event.inputs.LOCAL_VERSION_SUFFIX }}"' >> ./common/arch/arm64/configs/gki_defconfig
          fi

      - name: 7.3 删除 CONFIG_LOCALVERSION 中的 -4k 后缀（如果勾选）
        if: ${{ fromJSON(github.event.inputs.REMOVE_DEFAULT_4K_SUFFIX) }}
        run: |
          cd ${{ env.KERNEL_PLATFORM_DIR }}
          sed -i 's/-4k//' ./common/arch/arm64/configs/gki_defconfig

      - name: 8.1 设置构建时间戳
        run: |         
          if [ -n "${{ github.event.inputs.BUILD_TIMESTAMP }}" ]; then
            export SOURCE_DATE_EPOCH=$(date -d "${{ github.event.inputs.BUILD_TIMESTAMP }}" +%s)
            echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
          else
            echo "SOURCE_DATE_EPOCH=$(date +%s)" >> $GITHUB_ENV
          fi
      
      - name: Add sched_ext
        run: |
         cd ${{ env.KERNEL_PLATFORM_DIR }}
         git clone --depth=1 https://github.com/3620603660/sched_ext.git
         cp -r ./sched_ext/* ./common/kernel/sched
         rm -rf ./sched_ext/.git

      - name: 8.2 拉取afdo
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          git clone --depth=1 https://github.com/PxxPei/afdo.git

      - name: 9.1 安装和设置 Clang 19.0.0 编译器环境
        run: |
          mkdir -p clang19
          cd clang19
          wget -q https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240723-release/Clang-19.0.0git-20240723.tar.gz
          tar -zxf Clang-19.0.0git-20240723.tar.gz
          echo "CLANG_PATH=${{ github.workspace }}/clang19/bin" >> $GITHUB_ENV

      - name: 10.1 编译内核
        run: |
          export PATH="${{ env.CLANG_PATH }}:${PATH}"
          export PATH="/usr/lib/ccache:${PATH}"
          
          export KERNEL_TIME="${{ github.event.inputs.BUILD_TIMESTAMP }}"
          export KBUILD_BUILD_TIMESTAMP="${KERNEL_TIME:-$(date -u '+%a %b %d %H:%M:%S UTC %Y')}"
          export SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}

          export AFDO_PROFILE="${{ github.workspace }}/${{ env.WORKSPACE_DIR }}/afdo/kernel.afdo"
          if [ ! -f "$AFDO_PROFILE" ]; then
             echo "Error: AFDO profile not found at $AFDO_PROFILE"
              exit 1
          fi
          
          export KCFLAGS="-Wno-error -mllvm -thinlto-assume-merged -fauto-profile=$AFDO_PROFILE"
          echo "Using KCFLAGS: ${KCFLAGS}"
          
          export CC="ccache clang"
          export MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang \
          RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
          PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
          LD=ld.lld HOSTLD=ld.lld O=out SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"
          
          cd ${{ env.KERNEL_PLATFORM_DIR }}/common
          rm -rf out
          
          echo "开始编译内核..."
          export KBUILD_CFLAGS="-fpolly -flto=thin"
          make $MAKE_ARGS gki_defconfig
          make $MAKE_ARGS -j$(nproc)

          echo "✅ 内核编译完成"

      - name: 11.1 显示编译结果
        run: |
          cd ${{ env.KERNEL_PLATFORM_DIR }}/common
          if [ -f "out/arch/arm64/boot/Image" ]; then
            echo "✅ 内核镜像编译成功"
            ls -lh out/arch/arm64/boot/Image*
          else
            echo "❌ 内核镜像编译失败"
            exit 1
          fi
          
          mkdir -p ../dist
          cp out/arch/arm64/boot/Image ../dist/
          echo "✅ 内核编译成功！产物已复制到 dist 目录。"
          
      - name: 10.2 验证内核构建时间
        run: |
         strings kernel_workspace/kernel_platform/common/out/vmlinux | grep "UTC"

      - name: 11.1 准备 AnyKernel3 刷机包
        run: |
          cd kernel_workspace/kernel_platform/dist
          git clone https://github.com/3620603660/AnyKernel3.git AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          rm -f AnyKernel3/push.sh
          cp Image AnyKernel3/

      - name: 11.2 上传编译产物到 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_${{ github.event.inputs.DEVICE_CONFIG }}_${{ env.KSUVER }}
          path: kernel_workspace/kernel_platform/dist/AnyKernel3/*
          
      - name: 11.2 显示最终 ccache 统计信息
        run: |
          ccache -s


